[package]
name = "runtime"
description = "Runtime loop between the kernel and its drivers: spawn, timers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
arc-swap = { workspace = true }
audio = { workspace = true }
config = { workspace = true }
crossbeam-channel = { workspace = true }
fast_image_resize = { workspace = true }
fastrand = { workspace = true }
image = { workspace = true, features = ["bmp", "gif", "jpeg", "png", "webp"] }
kernel = { workspace = true }
library = { workspace = true }
notify = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
macos = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
