[package]
name = "audio"
description = "Playback engine: executes audio commands with rodio, reports audio events"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
crossbeam-channel = { workspace = true }
kernel = { workspace = true }
num-traits = { workspace = true }
realfft = { workspace = true }
rodio = { workspace = true }
thiserror = { workspace = true }
triple_buffer = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
