use crate::{
    domain::model::Model,
    update::{browse, config, library, player, server},
};

pub(crate) fn config_parts(model: &mut Model) -> config::ConfigParts<'_> {
    let Model {
        workspace,
        revisions,
        settings,
        themes,
        music_dir,
        library: _,
        scan_status: _,
        playlist: _,
        playlist_source: _,
        queue: _,
        player: _,
        transport: _,
        history: _,
        favorites: _,
        drivers: _,
        servers: _,
        downloads: _,
        catalog_name: _,
        catalogs: _,
        play_reports: _,
        covers: _,
    } = model;
    config::ConfigParts {
        workspace,
        revisions,
        settings,
        themes,
        music_dir,
    }
}

pub(crate) fn playback_parts(model: &mut Model) -> player::events::PlaybackParts<'_> {
    let Model {
        player,
        transport,
        playlist,
        queue,
        workspace,
        revisions,
        settings,
        library: _,
        music_dir: _,
        scan_status: _,
        playlist_source: _,
        history: _,
        favorites: _,
        themes: _,
        drivers: _,
        servers,
        downloads,
        catalog_name: _,
        catalogs: _,
        play_reports: _,
        covers: _,
    } = model;
    player::events::PlaybackParts {
        player,
        transport,
        playlist,
        queue,
        workspace,
        revisions,
        settings,
        servers,
        downloads,
    }
}

pub(crate) fn browse_parts(model: &mut Model) -> browse::BrowseParts<'_> {
    let Model {
        player,
        transport,
        playlist,
        queue,
        workspace,
        revisions,
        settings,
        library,
        favorites,
        scan_status,
        music_dir,
        playlist_source,
        history: _,
        themes: _,
        drivers: _,
        servers,
        downloads,
        catalog_name,
        catalogs,
        play_reports: _,
        covers: _,
    } = model;
    browse::BrowseParts {
        playback_parts: player::events::PlaybackParts {
            player,
            transport,
            playlist,
            queue,
            workspace,
            revisions,
            settings,
            servers,
            downloads,
        },
        library,
        favorites,
        scan_status,
        music_dir,
        playlist_source,
        catalog_name,
        catalogs,
    }
}

pub(crate) fn library_parts(model: &mut Model) -> library::LibraryParts<'_> {
    let Model {
        library,
        favorites,
        history,
        scan_status,
        music_dir,
        revisions,
        workspace,
        playlist,
        playlist_source,
        player,
        queue,
        transport: _,
        settings: _,
        themes: _,
        drivers: _,
        servers: _,
        downloads: _,
        catalog_name: _,
        catalogs: _,
        play_reports: _,
        covers: _,
    } = model;
    library::LibraryParts {
        library,
        favorites,
        history,
        scan_status,
        music_dir,
        revisions,
        workspace,
        playlist,
        playlist_source,
        player,
        queue,
    }
}

pub(crate) fn server_parts(model: &mut Model) -> server::ServerParts<'_> {
    let Model {
        servers,
        downloads,
        player,
        library: _,
        favorites,
        history: _,
        scan_status: _,
        music_dir: _,
        revisions,
        workspace,
        playlist,
        playlist_source,
        queue,
        transport: _,
        settings: _,
        themes: _,
        drivers: _,
        catalog_name,
        catalogs,
        play_reports,
        covers: _,
    } = model;
    server::ServerParts {
        servers,
        downloads,
        player,
        catalog_name,
        catalogs,
        revisions,
        favorites,
        workspace,
        playlist,
        playlist_source,
        play_reports,
        queue,
    }
}
